"use client";

import React, { useEffect, useState } from "react";
import { X, Save, Loader2 } from "lucide-react";
import FieldBuilder from "./FieldBuilder";
import KbSelector from "./KbSelector";
import { emptyAction, validateAction } from "@/lib/actions/schema";

const inputCls =
  "w-full rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-600 focus:border-cyan-500/50 focus:outline-none focus:ring-1 focus:ring-cyan-500/50";

export default function ActionDrawer({ open, initial, onClose, onSave }: any) {
  const [draft, setDraft] = useState<any>(emptyAction());
  const [errors, setErrors] = useState<any>({});
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (open && initial) {
      setDraft(structuredClone(initial));
      setErrors({});
    }
  }, [open, initial]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [open, onClose]);

  if (!open) return null;

  const set = (patch: any) => setDraft((d: any) => ({ ...d, ...patch }));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const errs = validateAction(draft);
    setErrors(errs);
    if (Object.keys(errs).length) return;
    setSaving(true);
    await new Promise((r) => setTimeout(r, 400));
    onSave(draft);
    setSaving(false);
    onClose();
  };

  const Err = ({ name }: { name: string }) =>
    errors[name] ? <p className="mt-1 text-xs text-red-400">{errors[name]}</p> : null;

  return (
    <div className="fixed inset-0 z-50">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />

      <form
        onSubmit={handleSubmit}
        className="absolute right-0 top-0 flex h-full w-full max-w-xl flex-col border-l border-zinc-800 bg-zinc-950 shadow-2xl"
        role="dialog"
        aria-modal="true"
      >
        <header className="flex items-center justify-between border-b border-zinc-800 px-6 py-4">
          <div>
            <h2 className="text-sm font-semibold text-zinc-100">
              {initial?.name ? "Modifica Azione" : "Nuova Azione"}
            </h2>
            <p className="mt-0.5 text-xs text-zinc-500">
              Configurazione per il motore Adaptive EOSv6
            </p>
          </div>
          <button type="button" onClick={onClose} className="rounded p-1.5 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200" aria-label="Chiudi">
            <X className="h-4 w-4" />
          </button>
        </header>

        <div className="flex-1 space-y-6 overflow-y-auto px-6 py-5">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-zinc-400">action_id</label>
              <input
                value={draft.action_id}
                onChange={(e) => set({ action_id: e.target.value })}
                placeholder="es. crm.enrich_lead"
                className={`${inputCls} font-mono text-xs`}
              />
              <Err name="action_id" />
            </div>
            <div>
              <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-zinc-400">Origine</label>
              <select
                value={draft.origin}
                onChange={(e) => set({ origin: e.target.value })}
                className={inputCls}
              >
                <option value="custom_partner">Custom Partner</option>
                <option value="autogenerated">Autogenerata dal Motore</option>
              </select>
            </div>
          </div>

          <div>
            <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-zinc-400">Nome</label>
            <input value={draft.name} onChange={(e) => set({ name: e.target.value })} placeholder="Nome leggibile dell'azione" className={inputCls} />
            <Err name="name" />
          </div>

          <div>
            <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-zinc-400">Descrizione</label>
            <textarea
              value={draft.description}
              onChange={(e) => set({ description: e.target.value })}
              rows={3}
              placeholder="Cosa fa questa azione e quando viene invocata dal motore…"
              className={`${inputCls} resize-none`}
            />
          </div>

          <KbSelector selected={draft.requires_kb} onChange={(requires_kb: any) => set({ requires_kb })} />

          <FieldBuilder
            label="Inputs"
            hint="Schema dei dati in ingresso"
            fields={draft.inputs}
            onChange={(inputs: any) => set({ inputs })}
          />
          {errors.inputs && <p className="-mt-3 text-xs text-red-400">{errors.inputs}</p>}

          <FieldBuilder
            label="Outputs"
            hint="Schema dei dati in uscita"
            fields={draft.outputs}
            onChange={(outputs: any) => set({ outputs })}
          />
          {errors.outputs && <p className="-mt-3 text-xs text-red-400">{errors.outputs}</p>}
        </div>

        <footer className="flex items-center justify-end gap-3 border-t border-zinc-800 px-6 py-4">
          <button type="button" onClick={onClose} className="rounded-md px-4 py-2 text-sm font-medium text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200">
            Annulla
          </button>
          <button
            type="submit"
            disabled={saving}
            className="inline-flex items-center gap-2 rounded-md bg-cyan-500 px-4 py-2 text-sm font-semibold text-zinc-950 transition-colors hover:bg-cyan-400 disabled:opacity-60"
          >
            {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            {saving ? "Salvataggio…" : "Salva Azione"}
          </button>
        </footer>
      </form>
    </div>
  );
}
