"use client";

import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import dynamic from "next/dynamic";
import { graphStratify, sugiyama, layeringSimplex, decrossOpt, coordQuad } from "d3-dag";
import { X, Database, ArrowRight, Activity } from "lucide-react";

const ForceGraph2D = dynamic(() => import("react-force-graph-2d"), {
  ssr: false,
  loading: () => (
    <div className="flex h-full w-full items-center justify-center text-sm text-zinc-500">
      Caricamento Grafo DAG EOSv6…
    </div>
  ),
});

const NODE_COLORS: Record<string, string> = {
  custom_partner: "#22d3ee", // cyan
  autogenerated: "#f59e0b",  // amber
  root: "#a78bfa",           // violet
};

const STATUS_RING: Record<string, string> = {
  active: "#10b981",
  pending: "#64748b",
  error: "#ef4444",
};

/* Calcolo del Layout DAG con d3-dag */
function computeDagLayout(rawNodes: any[], rawLinks: any[]) {
  if (!rawNodes.length) return { nodes: [], links: [] };

  try {
    const stratify = graphStratify();
    const dag = stratify(
      rawNodes.map((n) => ({
        id: String(n.id),
        parentIds: rawLinks
          .filter((l) => String(l.target) === String(n.id))
          .map((l) => String(l.source)),
      }))
    );

    const layout = sugiyama()
      .layering(layeringSimplex())
      .decross(decrossOpt())
      .coord(coordQuad());

    const { nodes: laidNodes } = layout(dag);

    const posById = new Map(
      laidNodes.map((n) => [n.data.id, { x: n.x * 140, y: n.y * 100 }])
    );

    return {
      nodes: rawNodes.map((n) => {
        const p = posById.get(String(n.id)) ?? { x: 0, y: 0 };
        return { ...n, fx: p.x, fy: p.y };
      }),
      links: rawLinks,
    };
  } catch (err) {
    // Fallback in caso di cicli o grafi non stratificabili
    return {
      nodes: rawNodes.map((n, idx) => ({ ...n, fx: idx * 100, fy: 0 })),
      links: rawLinks,
    };
  }
}

/* Pannello laterale dei dettagli nodo */
function DetailsPanel({ node, onClose }: { node: any; onClose: () => void }) {
  if (!node) return null;

  return (
    <aside className="w-80 shrink-0 border-l border-zinc-800 bg-zinc-950 p-5 font-sans text-zinc-200 overflow-y-auto">
      <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
        <h3 className="text-sm font-semibold text-zinc-100">{node.name}</h3>
        <button onClick={onClose} className="rounded p-1 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200">
          <X className="h-4 w-4" />
        </button>
      </div>

      <div className="mt-4 space-y-4 text-xs">
        <div>
          <span className="text-zinc-500">action_id:</span>
          <p className="font-mono text-cyan-400">{node.action_id || node.id}</p>
        </div>

        <div>
          <span className="text-zinc-500">Tipo & Stato:</span>
          <div className="mt-1 flex items-center gap-2">
            <span
              className="rounded px-2 py-0.5 text-[10px] font-medium uppercase"
              style={{ backgroundColor: `${NODE_COLORS[node.type]}20`, color: NODE_COLORS[node.type] }}
            >
              {node.type}
            </span>
            <span className="text-zinc-400">·</span>
            <span className="capitalize text-zinc-300">{node.status}</span>
          </div>
        </div>

        {node.description && (
          <div>
            <span className="text-zinc-500">Descrizione:</span>
            <p className="mt-0.5 leading-relaxed text-zinc-300">{node.description}</p>
          </div>
        )}

        <div>
          <span className="text-zinc-500">Inputs ({node.inputs?.length || 0}):</span>
          <pre className="mt-1 max-h-32 overflow-auto rounded bg-zinc-900 p-2 font-mono text-[11px] text-zinc-300">
            {JSON.stringify(node.inputs || [], null, 2)}
          </pre>
        </div>

        <div>
          <span className="text-zinc-500">Outputs ({node.outputs?.length || 0}):</span>
          <pre className="mt-1 max-h-32 overflow-auto rounded bg-zinc-900 p-2 font-mono text-[11px] text-zinc-300">
            {JSON.stringify(node.outputs || [], null, 2)}
          </pre>
        </div>

        <div>
          <span className="flex items-center gap-1 text-zinc-500">
            <Database className="h-3 w-3" /> KB Richieste:
          </span>
          <ul className="mt-1 space-y-1">
            {node.requires_kb?.length ? (
              node.requires_kb.map((kb: string) => (
                <li key={kb} className="rounded bg-zinc-900 px-2 py-1 font-mono text-[11px] text-zinc-400">
                  {kb}
                </li>
              ))
            ) : (
              <li className="text-zinc-600">Nessuna dipendenza KB</li>
            )}
          </ul>
        </div>
      </div>
    </aside>
  );
}

export default function EosGraph({ rawActions = [] }: { rawActions?: any[] }) {
  const fgRef = useRef<any>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [selected, setSelected] = useState<any>(null);
  const [dimensions, setDimensions] = useState({ width: 800, height: 600 });

  // Mappa le azioni del catalogo in Nodi e Archi DAG
  const dagInput = useMemo(() => {
    if (!rawActions.length) return { nodes: [], links: [] };

    const nodes = [
      { id: "root", name: "Trigger: Workflow EOSv6", type: "root", status: "active", action_id: "system.trigger" },
      ...rawActions.map((a) => ({
        id: a.id,
        name: a.name,
        type: a.origin,
        status: a.status,
        action_id: a.action_id,
        description: a.description,
        inputs: a.inputs,
        outputs: a.outputs,
        requires_kb: a.requires_kb,
      })),
    ];

    const links: { source: string; target: string }[] = [];

    // Collega l'elemento root alle azioni principali
    rawActions.forEach((a) => {
      // Se non ha dipendenze dirette da altri output, collegalo a root
      links.push({ source: "root", target: a.id });
    });

    return { nodes, links };
  }, [rawActions]);

  const graphData = useMemo(() => computeDagLayout(dagInput.nodes, dagInput.links), [dagInput]);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([e]) => {
      const { width, height } = e.contentRect;
      setDimensions({ width: Math.max(width, 300), height: Math.max(height, 300) });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  useEffect(() => {
    if (fgRef.current && graphData.nodes.length) {
      fgRef.current.zoomToFit(400, 50);
    }
  }, [graphData]);

  const paintNode = useCallback(
    (node: any, ctx: CanvasRenderingContext2D, globalScale: number) => {
      const r = 8;
      const color = NODE_COLORS[node.type] ?? "#64748b";

      if (selected?.id === node.id) {
        ctx.beginPath();
        ctx.arc(node.x, node.y, r + 5, 0, 2 * Math.PI);
        ctx.strokeStyle = "#ffffff";
        ctx.lineWidth = 2;
        ctx.stroke();
      }

      ctx.beginPath();
      ctx.arc(node.x, node.y, r, 0, 2 * Math.PI);
      ctx.fillStyle = color;
      ctx.fill();
      ctx.lineWidth = 2;
      ctx.strokeStyle = STATUS_RING[node.status] ?? "#334155";
      ctx.stroke();

      const label = node.name;
      const fontSize = 11 / globalScale;
      ctx.font = `${fontSize}px sans-serif`;
      ctx.textAlign = "center";
      ctx.textBaseline = "top";
      ctx.fillStyle = "#e2e8f0";
      ctx.fillText(label, node.x, node.y + r + 3 / globalScale);
    },
    [selected]
  );

  return (
    <div className="flex h-[calc(100vh-140px)] w-full overflow-hidden rounded-lg border border-zinc-800 bg-zinc-950">
      <div ref={containerRef} className="relative flex-1">
        <ForceGraph2D
          ref={fgRef}
          graphData={graphData}
          width={dimensions.width}
          height={dimensions.height}
          nodeRelSize={8}
          dagMode={null}
          d3VelocityDecay={0.4}
          cooldownTicks={0}
          enableNodeDrag={false}
          linkDirectionalArrowLength={5}
          linkDirectionalArrowRelPos={1}
          linkColor={() => "#27272a"}
          linkWidth={1.5}
          linkDirectionalParticles={3}
          linkDirectionalParticleSpeed={0.005}
          linkDirectionalParticleWidth={2.5}
          linkDirectionalParticleColor={() => "#22d3ee"}
          nodeCanvasObject={paintNode}
          onNodeClick={(node) => setSelected(node)}
          backgroundColor="#09090b"
        />

        <div className="absolute left-4 top-4 flex items-center gap-4 rounded-md border border-zinc-800 bg-zinc-900/80 px-3 py-1.5 text-xs backdrop-blur-sm">
          <Legend color={NODE_COLORS.root} label="Trigger" />
          <Legend color={NODE_COLORS.custom_partner} label="Custom Partner" />
          <Legend color={NODE_COLORS.autogenerated} label="Autogenerata" />
        </div>
      </div>

      <DetailsPanel node={selected} onClose={() => setSelected(null)} />
    </div>
  );
}

function Legend({ color, label }: { color: string; label: string }) {
  return (
    <span className="flex items-center gap-1.5 font-medium text-zinc-400">
      <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: color }} />
      {label}
    </span>
  );
}
