"use client";

import React from "react";
import { Search, X } from "lucide-react";

const FILTERS = [
  { value: "all", label: "Tutte" },
  { value: "custom_partner", label: "Custom Partner" },
  { value: "autogenerated", label: "Autogenerate" },
];

export default function Toolbar({ query, onQuery, filter, onFilter }: any) {
  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="relative w-full sm:max-w-sm">
        <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500" />
        <input
          value={query}
          onChange={(e) => onQuery(e.target.value)}
          placeholder="Cerca azioni, action_id, descrizione…"
          className="w-full rounded-md border border-zinc-800 bg-zinc-900 py-2 pl-9 pr-8 text-sm text-zinc-100 placeholder:text-zinc-500 focus:border-cyan-500/50 focus:outline-none focus:ring-1 focus:ring-cyan-500/50"
        />
        {query && (
          <button
            onClick={() => onQuery("")}
            className="absolute right-2 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
            aria-label="Cancella ricerca"
          >
            <X className="h-4 w-4" />
          </button>
        )}
      </div>

      <div className="inline-flex rounded-md border border-zinc-800 bg-zinc-900 p-0.5">
        {FILTERS.map((f) => (
          <button
            key={f.value}
            onClick={() => onFilter(f.value)}
            className={`rounded px-3 py-1.5 text-xs font-medium transition-colors ${
              filter === f.value
                ? "bg-zinc-700 text-white"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>
    </div>
  );
}
