export const DATA_TYPES = ["string", "number", "boolean", "object", "array", "date", "uuid"];

export const ACTION_TYPES: Record<string, { label: string; tone: string }> = {
  custom_partner: { label: "Custom Partner", tone: "cyan" },
  autogenerated: { label: "Autogenerata", tone: "amber" },
};

export const KB_CATALOG = [
  { id: "kb://crm/schema-v2", name: "CRM Schema v2", scope: "partner" },
  { id: "kb://scoring/model-eosv6", name: "Modello Scoring EOSv6", scope: "engine" },
  { id: "kb://billing/plans", name: "Piani Billing", scope: "partner" },
  { id: "kb://geo/eu-regulations", name: "Regolamentazioni EU", scope: "engine" },
  { id: "kb://nlp/intents-it", name: "Intenti NLP (IT)", scope: "engine" },
];

export function validateField(field: any) {
  if (!field.key?.trim()) return "La chiave è obbligatoria";
  if (!/^[a-z][a-z0-9_]*$/i.test(field.key.trim()))
    return "Solo lettere, numeri e underscore (deve iniziare con una lettera)";
  if (!DATA_TYPES.includes(field.type)) return "Tipo non valido";
  return null;
}

export function validateAction(action: any) {
  const errors: Record<string, string> = {};
  if (!action.action_id?.trim()) errors.action_id = "Obbligatorio";
  else if (!/^[a-z][a-z0-9_.-]*$/i.test(action.action_id.trim()))
    errors.action_id = "Formato: lettere, numeri, punto, trattino";
  if (!action.name?.trim()) errors.name = "Obbligatorio";
  for (const f of action.inputs || []) {
    const e = validateField(f);
    if (e) { errors.inputs = `Input "${f.key || "(vuota)"}": ${e}`; break; }
  }
  for (const f of action.outputs || []) {
    const e = validateField(f);
    if (e) { errors.outputs = `Output "${f.key || "(vuota)"}": ${e}`; break; }
  }
  return errors;
}

export function emptyField() {
  return { key: "", type: "string", required: false };
}

export function emptyAction() {
  return {
    id: crypto.randomUUID(),
    action_id: "",
    name: "",
    description: "",
    origin: "custom_partner",
    requires_kb: [],
    inputs: [emptyField()],
    outputs: [emptyField()],
    status: "pending",
    updated_at: new Date().toISOString(),
  };
}

let _actions = seed();
const listeners = new Set<Function>();

function seed() {
  const now = new Date().toISOString();
  return [
    {
      id: crypto.randomUUID(),
      action_id: "crm.enrich_lead",
      name: "Enrich Lead CRM",
      description: "Arricchisce il profilo lead con dati anagrafici e firmografici dal CRM partner.",
      origin: "custom_partner",
      requires_kb: ["kb://crm/schema-v2"],
      inputs: [
        { key: "lead_id", type: "uuid", required: true },
        { key: "include_firmo", type: "boolean", required: false },
      ],
      outputs: [
        { key: "profile", type: "object", required: true },
        { key: "confidence", type: "number", required: true },
      ],
      status: "active",
      updated_at: now,
    },
    {
      id: crypto.randomUUID(),
      action_id: "engine.score_lead",
      name: "Scoring Lead",
      description: "Calcola il punteggio di qualità del lead usando il modello di scoring interno.",
      origin: "autogenerated",
      requires_kb: ["kb://scoring/model-eosv6"],
      inputs: [{ key: "profile", type: "object", required: true }],
      outputs: [{ key: "score", type: "number", required: true }],
      status: "active",
      updated_at: now,
    },
  ];
}

export const actionsStore = {
  getAll: () => [..._actions],
  subscribe(fn: Function) { listeners.add(fn); return () => listeners.delete(fn); },
  emit() { listeners.forEach((fn) => fn([..._actions])); },
  upsert(action: any) {
    const i = _actions.findIndex((a) => a.id === action.id);
    const next = { ...action, updated_at: new Date().toISOString() };
    if (i >= 0) _actions[i] = next; else _actions = [next, ..._actions];
    this.emit();
    return next;
  },
  remove(id: string) { _actions = _actions.filter((a) => a.id !== id); this.emit(); },
};
